### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[ci skip]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
For now I just changed the typo in this one file. It's in a lot of files.

Also what I can't change, the tag-line:

>C# sharp style generators a.k.a. semi-coroutines for Julia.

As "sharp" there is redundant, I could maybe change to "C#-style" with hyphen (and skip the period in the end; not a full sentence).

**Comment by PallHaraldsson** [comment]
One question, the direct approach seems faster, I was just looking into how to do yield since it in the fastest program (Chapel) there: https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/pidigits-chapel-4.html and I wanted to copy/translate that implementation.

Do you know, since I can't use a package for that competition, is there a way to get equivalent code, as from using a macro, e.g. yours. I mean a macro just rewrites the AST, but is there a way to generate the source code after its changes? It might not be too important, as if I understand this correctly, the direct approach is faster. So is that not what you should get out? I'm not sure why Chapel is this fast while using "yield".

**Comment by BenLauwens** [comment]
Thanks! I have included your proposed modifications. The direct code is no longer necessarily faster, see new benchmarks ... I will implement the pidigits algorithm with @resumable functions ...

**Comment by BenLauwens** [comment]
Hi 

I implemented a `@resumable function` that is based on the Chapel version. (see examples;)
Speed is similar to the fastest Julia implementation.
I understand that you can not use a package but the code that is generated is the following:

```julia
mutable struct var"##254" <: ResumableFunctions.FiniteStateMachineIterator{Any}
    _state::UInt8
    accum::BigInt
    d::UInt64
    k::Int64
    tmp1::BigInt
    tmp2::BigInt
    numer::BigInt
    denom::BigInt
    k2::Int64
    function var"##254"(; )
        fsmi = new()
        fsmi._state = 0x00
        fsmi
    end
end
function pidigits(; )
    fsmi = var"##254"()
    fsmi
end
function (_fsmi::var"##254")(_arg::Any = nothing; )
    _fsmi._state === 0x00 && @goto(_STATE_0)
    _fsmi._state === 0x01 && @goto(_STATE_1)
    error("@resumable function has stopped!")
    @label _STATE_0
    _fsmi._state = 0xff
    _arg isa Exception && throw(_arg)
    _fsmi.k = 1
    _fsmi.d = UInt64(0)
    _fsmi.numer = BigInt(1)
    _fsmi.denom = BigInt(1)
    _fsmi.accum = BigInt(0)
    _fsmi.tmp1 = BigInt(0)
    _fsmi.tmp2 = BigInt(0)
    while true
        _fsmi.k2 = 2 * _fsmi.k + 1
        addmul_ui!(_fsmi.accum, _fsmi.numer, 2)
        mul_ui!(_fsmi.accum, _fsmi.k2)
        mul_ui!(_fsmi.denom, _fsmi.k2)
        mul_ui!(_fsmi.numer, _fsmi.k)
        _fsmi.k += 1
        if _fsmi.numer <= _fsmi.accum
            mul_ui!(_fsmi.tmp1, _fsmi.numer, 3)
            add!(_fsmi.tmp1, _fsmi.accum)
            tdiv_q!(_fsmi.tmp2, _fsmi.tmp1, _fsmi.denom)
            _fsmi.d = get_ui(_fsmi.tmp2)
            mul_ui!(_fsmi.tmp1, _fsmi.numer, 4)
            add!(_fsmi.tmp1, _fsmi.accum)
            tdiv_q!(_fsmi.tmp2, _fsmi.tmp1, _fsmi.denom)
            if _fsmi.d == get_ui(_fsmi.tmp2)
                _fsmi._state = 0x01
                return _fsmi.d
                @label _STATE_1
                _fsmi._state = 0xff
                _arg isa Exception && throw(_arg)
                submul_ui!(_fsmi.accum, _fsmi.denom, _fsmi.d)
                mul_ui!(_fsmi.accum, 10)
                mul_ui!(_fsmi.numer, 10)
            end
        end
    end
end
```

You can eliminate the `_arg` processing to make it even faster ;)

Kind regards

Ben

**Pull request closed without merging**
